# Backend Docker Compose
version: "3.7"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: pet_home
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: always
    networks:
      - fit_a_pet

networks:
  fit_a_pet:
    driver: bridge