# Backend Docker Compose
version: "3.7"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: pet_home
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: always
    networks:
      - fit_a_pet

  rdb1:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fit_a_pet
      POSTGRES_PASSWORD: fit_a_pet
      POSTGRES_DB: fit_a_pet
      TZ: Asia/Seoul
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - fit_a_pet

networks:
  fit_a_pet:
    driver: bridge

    external: true